### ISSUE TITLE
Embed player to .md file

### ISSUE THREAD

**Issue by skyfore** [asciinema/asciinema-player#103]
How can I embed asciinema-player `without` React ?

I am write README.md with `mkdocs`, and somewhere I want to embed player to my `.md` file. But when load asciinema-player.js I get some error such as 

![image](https://user-images.githubusercontent.com/7485049/50447273-f98a3d00-0954-11e9-8fea-530ea5f44a3e.png)

**Comment by mathieu-aubin** [comment]
Maybe you can be more precise? 
Its hard to fully understand your issue without knowing what you are trying to achieve exactly and in what ways you are trying to do it.

player js file is meant to be used in html sources, which can load javascript (with the use of a browser that is).

Markdown isn’t a file format that would allow loading javascript since it’s not mesnt to be loaded/parsed/« executed » by a browser

**Comment by skyfore** [comment]
OK, I just use player.js in my .html by

```javascript
<script src="player.js"></script>
```

But get error such as `Module name "react" has not been loaded `

**Comment by mathieu-aubin** [comment]
Again, there is problem with how you describe what you are doing in a way that we can clearly see what you are doing. Simply stating that you add a js source one way - and posting a very generic code for that matter - doesnt help.

Best would be for you to post your entire (no matter how small or irrelevant you might think they are) source files. You should/must follow the basics.

I dont want to risk confusing you more than helping  so i suggest you take a look at the following link (actually, maybe a complete read of the document would also help you be on the right track)

https://github.com/asciinema/asciinema-player#self-hosting-quick-start

**Comment by skyfore** [comment]
Thinks for help~
