### ISSUE TITLE
All recordings are cut off on the right side

### ISSUE THREAD

**Issue by Bios-Marcel** [asciinema/asciinema-player#109]
So I was recording my terminal which was in full screen on my 1920x1080 screen and the output was a 4:3 ratio asciinema recording. Is it supposed to be like that?

**Comment by mathieu-aubin** [comment]
here is what i get for output when viewing the asciicast with the following environment

- _Firefox_ 66.0b12 (64-bit)
- linux _Fedora_ 29
- 1920x1080
- Browser window zoomed to 120% (content target focus) and set to fullscreen (to get rid of useless stuff ie: taskbars and the likes)
- Full screen recording using [Simple Screen Recorder](https://github.com/MaartenBaert/ssr)

basically, i don't see any apparent issues with my setup (and any other i have tried)

if it can be of help, i can show the output using different browsers at different resolutions (midori, chrome, opera...)

[gh-asciinema-player.issue_109.zip](https://github.com/asciinema/asciinema-player/files/3001124/gh-asciinema-player.issue_109.zip)

##### \* *Note:* I had to zip the mp4 in order to post it here

**Comment by mathieu-aubin** [comment]
@JARIS101 

> Just tried it on a big big screen, Works well for me.

i too was under the impression it was all fine until i checked all other screenshots and realized i was missing and entire column on the left side of the asciicast. I made me think there was nothing wrong with the output as it doesn't show any signs of it being cropped in any way.

Check the screenshots that have been posted regarding this issue and you might also (like i did with my last post) edit your comment.

**Comment by issadarkthing** [comment]
any updates for this issue? Im currently having the same issue as well

**Comment by sickill** [comment]
The latest version of the player (3.0) has been completely rewritten (see [my post about it](https://blog.asciinema.org/post/smaller-faster/)) and it uses vastly improved sizing/fitting model. Nothing should be cut off anymore, because the text is now automatically scaled to fit the available screen real estate.

This is how it looks for me now:

<img width="1020" alt="Zrzut ekranu 2021-12-11 o 14 00 54" src="https://user-images.githubusercontent.com/17589/145677394-56c56b4d-7fa6-4e6d-8665-503ac3db849d.png">

**Comment by Bios-Marcel** [comment]
The old recording seems to work fine now.

**Comment by ahillio** [comment]
Is asciinema.org still using the old player?  https://asciinema.org/a/ufajzNUqzIYoI6f7cszzoUfFJ shows the recording as cropped.  The recording I'm working on right now https://asciinema.org/a/455630 is also cropped on the right side.

**Comment by ahillio** [comment]
@sickill any idea why it still look like this for me?
![Screenshot_20211212_101423](https://user-images.githubusercontent.com/5461756/145718044-6de32659-8db8-46f0-aa3c-f58260bca087.png)

**Comment by ahillio** [comment]
![Screenshot_20211212_101719](https://user-images.githubusercontent.com/5461756/145718177-4bf05105-e699-47fd-ad5d-df98e86064e7.png)

**Comment by sickill** [comment]
What browser and version you use @ahillio ?

**Comment by ahillio** [comment]
Firefox Version 95.0 (64-bit) on Ubuntu.

**Comment by rrwright** [comment]
@sickill It's also broken in Safari 15.5 on macOS 12.4. Seems to work fine in Chrome 103.0.5060.114 on the same macOS.

If I hadn't found this thread, I would never have guessed it was a browser rendering problem. I thought it was a recording problem and was about to abandon Asciinema.
