### ISSUE TITLE
Breaks possibly when using `\r` 

### ISSUE THREAD

**Issue by bucaran** [asciinema/asciinema-player#16]
Here is the problem screncast: https://asciinema.org/a/46220mbeu2302v0lihzu0xa2z

Here is an example that works using an alternative program, just for reference and to understand the output that I was expecting: http://showterm.io/ddd89744639247bc98daf

Thanks and Happy New Year!

**Comment by sickill** [comment]
`\r` is working fine. The problem is the printed lines are longer then terminal width (columns number) saved in the asciicast file. The file has width set to 100, but it seems your terminal during recording had 102 columns (and possibly got resized to 100 just before the end of the recording?).

I have changed set width to 102 and re-uploaded your asciicast, looks fine: https://asciinema.org/a/blvyuorz7ocn2r1q5tksq2ahn

Can you try recording this again? Are you by any chance using a tiling WM (which could do layout reflow or something during the recording)?

**Comment by bucaran** [comment]
@sickill This could be the issue then. I will try again and keep you posted.
