### ISSUE TITLE
Issue: first word of command printed on newline when using tmux

### ISSUE THREAD

**Issue by sbmsr** [asciinema/asciinema-player#202]
When hitting enter, I am seeing the first word of my command printed on the new line.

[Here is a video example](https://asciinema.org/a/548436)

and here is a picture:

<img width="670" alt="image" src="https://user-images.githubusercontent.com/2349518/210684353-94e93192-8f49-4c9e-a281-1642b1e0e572.png">

What is odd, is that this issue always occurs within Tmux, and also occurs within iTerm 2 (with or without tmux). The only way i have been able to avoid it is by using the native mac terminal. 

I've seen various tmux session recordings without this issue, which leads me to believe it may be an issue with one of my local configs.

Shell: zsh + oh my zsh
OS: mac OS Monterrey 12.6

PS - thanks for building this awesome tool. I'll be using the workaround for now, but wanted to help track this issue.

**Comment by sickill** [comment]
I replayed your recording in terminal with `asciinema play` and it prints "git" on the 2nd line there too. I tested on Gnome Terminal and Alacritty. So asciinema-player behaviour is consistent with popular terminal emulators our there. Given that I'm going to close this.

If you believe this extra "git" is there because of asciinema recorder feel free to re-open this at https://github.com/asciinema/asciinema
