### ISSUE TITLE
Feature Request: Beep

### ISSUE THREAD

**Issue by alexisart** [asciinema/asciinema-player#219]
I would like to request sound be added to the javascript player. https://asciinema.org/a/569009

The CLI can already play the sound, but the website is lacking that functionality. `asciinema play https://asciinema.org/a/569009`

**Comment by sickill** [comment]
The reason it works in a terminal is that your terminal handles this command, not `asciinema play`, there isn't any code to handle that in the cli.

While I can see value in having beep (0x07) work in a terminal in general, where it can bring your attention to something, or tell you that there's no auto-completion etc, I don't really see a point in having it in the player. You already pay attention to the played recording, and you can't act on the beep. Am I missing some use case?

**Comment by alexisart** [comment]
The beep will help increase entertainment value. For example, this recording uses beeps as part of the Jurassic Park simulation. https://asciinema.org/a/444386

You can hear it in terminal, but would never know it exists if using web only

**Comment by ludolpif** [comment]
> The beep will help increase entertainment value. For example, this recording uses beeps as part of the Jurassic Park simulation. https://asciinema.org/a/444386

Hi @alexisart , you may be interested by what I've done around #220. Don't assume my code is portable (the sound part I wrote last night) nor it works out of the box with asciinema 3.2.0 (because updateTerminal event don't return data). But if you duplicate my POC including the modified asciinema.min.js, you can build a page with sound for any characters outputed on terminal, including special ones like beep. Including sound in asciinema is getting the thing bigger, asking for a event extra arg may be fine for sickill, the original author and allow to buid an html page around that goes beeeeep :)

**Comment by alexisart** [comment]
I'll have to take a deeper look into this, but I was looking into if one could play music in the terminal via ansi codes. This is what came up. http://artscene.textfiles.com/ansimusic/

**Comment by sickill** [comment]
Maybe what I implement here https://github.com/asciinema/asciinema-player/pull/222 could be useful?

It exposes input events (key presses), but I could see how you could for example assign different sound (or pitch) to different key presses this way.

**Comment by sickill** [comment]
No plans for implementing beep at the moment.
