### ISSUE TITLE
Vim colors rendered incorrectly with TERM=xterm-kitty

### ISSUE THREAD

**Issue by rnevius** [asciinema/asciinema-player#231]
As above. Colors render correctly when manually setting `TERM=xterm-256color`, but incorrectly with `TERM=xterm-kitty`. 

[Kitty](https://sw.kovidgoyal.net/kitty/index.html) is a popular terminal emulator.

**Comment by EgZvor** [comment]
You might want to check out this thread https://github.com/vim/vim/issues/11716 and this advice from Kovid https://sw.kovidgoyal.net/kitty/faq/#using-a-color-theme-with-a-background-color-does-not-work-well-in-vim (which I applied and is what breaks the highlighting in asciinema).

**Comment by sickill** [comment]
Thanks for the context. This actually explains a lot. I suspect the use of non-standard `:` instead of `;` in color related escape sequences.

**Comment by kovidgoyal** [comment]
> Thanks for the context. This actually explains a lot. I suspect the use of non-standard `:` instead of `;` in color related escape sequences.

Note that colon is standard, from ECMA-48. semi-colon is non-standard but more common, IIRC konsole first started erroneously using semi-colon and it spread from there. Most modern terminal emulators support both forms. You should too.

To be didactic, the reason colon is used is because it encodes sub-parts of a single specification. SGR escape codes can actually contain multiple semi-colon separated parts (though this is rarely used in practice). In the presence of multiple parts separating sub-parts with semi-colons is ambiguous. Therefore, colons should always be used for sub-parts.

**Comment by sickill** [comment]
Yeah, that makes a lot of sense. Thanks. 

We'll need to implement support for it in https://github.com/asciinema/avt

**Comment by ku1ik** [comment]
This has been fixed in 3.8.0 - https://github.com/asciinema/asciinema-player/releases/tag/v3.8.0
