### ISSUE TITLE
v3 player is harder to style than v2

### ISSUE THREAD

**Issue by mholt** [asciinema/asciinema-player#246]
Hi -- I just want to say I've only had a couple use cases for asciinema, but it has been awesome to use every time, and I always enjoy coming across an asciicast (especially in place of a video of a terminal) -- so I really appreciate this project!

**Describe the bug**
When I made [this page](https://caddyserver.com/v2) a few years ago, I was using I think v2.6.1 of the player. You'll notice it has an asciinema player a little down the page on the left. Notice that it's been styled to have padding around the terminal element.

Now I'm trying to make a new webpage with v3.6.1 and having some trouble recreating the look. The new version seems to rely on `box-sizing: content-box` and manually setting a width/height instead of simply using 100% of a container. This is problematic because I can't seem to make the player look the way I want 😅

Here's a screenshot of the look I had on the linked page above, with asciinema player v2 with all the CSS needed to style it:

<img width="682" alt="image" src="https://github.com/asciinema/asciinema-player/assets/1128849/2c416b41-2fb7-4994-bf07-96148f5501a9">

```css
.asciinema-player-wrapper .asciinema-player {
	box-shadow: -10px 10px 15px rgba(0, 0, 0, 0.25);
	border-radius: 8px;
}

.asciinema-terminal {
	border: none;
	padding: 10px;
	padding-bottom: 35px; /* for when the control bar is visible */
}
```

Notice how there is padding around the terminal so it looks kind of like a computer monitor 😄 (see the white bar especially) It's very simple, I just set `padding: 10px` and remove the border.

And here's the closest I can get with v3 with the relevant CSS:

<img width="747" alt="image" src="https://github.com/asciinema/asciinema-player/assets/1128849/a82f45c2-dc9c-4212-b16f-c48af130dbfe">

```css

div.ap-wrapper div.ap-player {
	box-shadow: 10px 10px 15px rgba(0, 0, 0, 0.25);
	border-radius: 10px;
}

.asciinema-theme-asciinema pre.ap-terminal {
	padding: 20px;
	border: none;
	background-color: transparent;
	top: -10px;
	left: -10px;
	position: relative;
}
```

A few things to notice here:

- The white bar goes off the end of the container to the right.
- The selectors have to be (unnecessarily?) specific in order to match specificity within the asciinema CSS -- or I use `!important` ... this is not a big deal, but is a bit tedious and seems more difficult to maintain.
- I have to double the padding and adjust the relative position of the terminal to the actual padding I want. But as you can see, this still runs off the right side.

I've tried a few things. If I simply remove the border and don't do anything else like set padding or left/top, the width is still wrong (again, notice the right side of the white bar):

<img width="714" alt="image" src="https://github.com/asciinema/asciinema-player/assets/1128849/55d7d454-ba26-4bab-ab7e-7ecba1514209">

Basically, I'm just having trouble getting the player to constrain the contents of the terminal to _within_ the padding.

See "Expected behavior" below for what I hope we can achieve. :)

**To Reproduce**
(Kind of n/a -- but I'll explain)

**Expected behavior**
I'm hoping that the current version of asciinema player can be made as easy to style as v2.

I believe the easiest fix -- hopefully -- is to set the player size based on `box-sizing: border-box` instead of `box-sizing: content-box`. This mostly has the desired effect when I set that myself, except that the width/height properties are set with `content-box`, i.e. regardless of padding, so no matter what I do in CSS, the width/height dimensions cause the terminal to exceed its container.

Can the size of the terminal use 100% width and height? I noticed that v2 still apparently calculates width+height dimensions and sets them, but it at least does so correctly (or with regards for padding). I'm hoping we can restore that behavior in v3, since it feels like a regression.

**Screenshots**
(See above)

**Versions:**
 - OS: macOS 13.5
 - Browser Safari and Chrome
 - asciinema player: 3.6.1 (coming from 2.6.1)

**Additional context**

Thank you for this awesome and unique project! I hope my issue makes sense. It's mostly a gripe/nit, that is probably not important in the grand scheme, but this will likely become _the prominent feature_ right at the top of the new homepage for Caddy in the coming months. It will be the first thing tens of thousands of people will see, so I do want it to be perfect if possible. 🤞  Thanks!

**Comment by ku1ik** [comment]
Hey Matt,

Thanks for the kind words. Awesome that you find asciinema useful and that you use it on Caddy's website.
In fact I'm happy user of Caddy for a few years now and both https://asciinema.org and https://blog.asciinema.org are fronted with Caddy. Works great!

That "monitor" styling you created there looks amazing, love it! With it the player looks like it came from Apple :smile: 

Regarding the padding/width problem: v3 uses different (I believe better) algorithm for fitting the player in the container. It uses container's width/height and adjusts font size appropriately so the the terminal makes use of all the available space while preserving aspect ratio. I don't remember exactly but I think using `box-sizing: content-box` made it way easier.

You may try `fit: false` option, which mimics sizing behavior of v2. https://github.com/asciinema/asciinema-player#fit
Other than that I don't have another immediate workaround in mind, but I'll experiment with the CSS you provided and will get back to you shortly.

Regarding more need for more specific selectors: this is to prevent style clash on people's websites. I think the only major change I did in this regard was prefixing most classes with `ap-` (which stands for "ascinema player"), so it's harder to accidentally break player's style with your page's one. I may have also put some styles under nested selectors, which is probably why you need sth like `div.ap-wrapper div.ap-player` instead of just `div.ap-player`. That's good feedback, and I agree it makes sense to make it easier. I'll add that to my improvements list for sure.

**Comment by mholt** [comment]
Gotcha, thank you for the quick reply :smiley:

Ha, I didn't know you used Caddy for asciinema -- that's awesome!

Oh I have no doubts v3 is superior -- it's why I want to use it. I just need to find a way to add padding to the terminal. When I boil it down, that is the goal.

Unfortunately `fit: false` doesn't have the desired effect :( The content overflows the size of my container, quite a lot actually:

<img width="802" alt="image" src="https://github.com/asciinema/asciinema-player/assets/1128849/851a0124-ef5a-4b88-80ff-d86e8c785cd1">

(even with a max-width set, the width doesn't overflow but the content does 🙃 )

> Regarding more need for more specific selectors: this is to prevent style clash on people's websites. I think the only major change I did in this regard was prefixing most classes with ap- (which stands for "ascinema player"), so it's harder to accidentally break player's style with your page's one. I may have also put some styles under nested selectors, which is probably why you need sth like div.ap-wrapper div.ap-player instead of just div.ap-player. That's good feedback, and I agree it makes sense to make it easier. I'll add that to my improvements list for sure.

Oh I totally understand that, it was my guess too. The v2 player used a custom element, `asciinema-player`, which I quite liked (I guess it was changed to a `div` for a reason?)

Anyway, this is not a major issue. I might suggest, though, that instead of this: `div.ap-wrapper div.ap-player` -- maybe just do `.ap-player` -- since it's already prefixed by `ap-` to avoid collisions. But, if you find that you're getting reports of conflicts from your users, perhaps `.ap-wrapper .ap-player` -- but I don't know if the `div` prefix is adding any value 🤷‍♂️ (These are just my very unimportant 2 cents)

---

Thanks for looking at this and helping me find a solution! Again, the goal is simply the look of the player on the caddyserver.com/v2 page -- with the padding around the terminal. How that is achieved, unless it's horribly hacky, is less important to me; I'm hoping that there can be a pretty decent CSS solution, I just haven't found it. I suspect the sizing algorithm could use minor adjustments to accommodate. (But maybe not!)

Thanks again for a great project :+1:

**Comment by ku1ik** [comment]
Ok, so the reason why it's not so easy is due to the fact that the border is meant it be expressed in `em` (here is 0, so doesn't matter) and the algorithm assumes 0 padding. But you can do it with no padding and instead rely on (transparent) border.

This is what I did:

```css
div.ap-wrapper div.ap-player {
    background: #333 linear-gradient(135deg, rgba(0, 0, 0, 0) 0%,rgba(125, 125, 125, 0.5) 46%,rgba(45, 45, 45, 0.5) 46.5%,rgba(0, 0, 0, 0) 100%);
}

.ap-player pre.ap-terminal {
    background-color: transparent;
    border-color: transparent;
}
```

And how it looks:

![Screenshot from 2023-09-18 09-52-39](https://github.com/asciinema/asciinema-player/assets/17589/883ed6a1-825e-4971-bed9-42e8ec9b36b1)

This uses default border of `0.75em`. 

You can add extra `pre.ap-terminal { border-width: 0.5em  }` to tweak border size (which would really act as padding given border is transparent). Important: that `border-width` must be put on `pre.ap-terminal` alone, without nesting it under anything (like we did for the transparency). The reason for that is the player creates a temporary terminal element in DOM upon initialization to do font measurements, but that terminal element is not placed inside `.ap-player`. I guess this made it whole lot trickier as you didn't know about this measurement step.

I hope this does it for you.

**Comment by mholt** [comment]
Ah -- yes, that looks great in that screenshot -- and I think I know what's going on now! Thank you!

It turns out that the [caddyserver.com/v2](https://caddyserver.com/v2) page only happens to look "correct" at exactly that size. If the page width is resized to be narrower (including viewing on a mobile screen), even the v2 player just chops content off the right side. v3 _is better_ because it actually resizes on-the-fly:

https://github.com/asciinema/asciinema-player/assets/1128849/731abe8d-e9fa-4718-a1e0-7538c26f3760

(I have removed some of the extra styles for clarity and simplification.)

This same resizing phenomenon occurs on the official asciinema website as well, so I guess that's expected. It's probably tricky because you have to maintain a correct aspect ratio based on char size. So that's understandable.

In other words, at the width my webpage was displaying the terminal, it just so happened to be one of those that cuts off the content on the side.

I wonder if this appearance at variable widths could be improved a bit.

For example, I made this change to the CSS:

```diff
pre.ap-terminal {
-   margin: 0px;
+   margin: 0px auto;
}
```

and now for sizes where the content doesn't fill the width of the terminal, at least the content is centered:

<img width="592" alt="image" src="https://github.com/asciinema/asciinema-player/assets/1128849/5c345a7b-22ed-47f2-becb-c50a06e27ab9">

Currently there are clearly discrete resize points. Is there is a way to scale both text and the container together without discrete steps? i.e. if I drag my window to be smaller, the text could just scale down its size based on the width. (I think the CSS unit `vw` does this for us, I see we're currently using `%` -- maybe that's more correct anyway, I dunno.)

Of course there should be a minimum size, at which point I suppose chopping off content (and maybe making it scrollable? -- or wrapping) is the right thing to do.

Maybe / hopefully there's a way to preserve the defined padding regardless of container size.

What do you think? (Thank you again so much for your help!)

**Comment by ku1ik** [comment]
That discrete scaling, that's only in Safari, so I assume you test this on Safari. It's due to Safari's discrete font-size behaviour, it doesn't do it well when font-size is specified in %, which the whole auto-scaling/responsiveness is based on here. This is a known old issue in Safari. Check it out in Firefox or Chrome - it's smooth as you'd expect.

**Comment by mholt** [comment]
OH wow. You're right. 🤦 I'll leave that one for Webkit to fix!

Thank you for your time and effort on this. LGTM and we're excited to use it at the top of our homepage!

**Comment by ku1ik** [comment]
In relation to another bug report I tested once again on Safari and it looks like on Safari 17.3 the discrete scaling bug is no more. They probably fixed it in the initial Safari 17 release, which was out on Sep 18, 2023, the same day you posted your last comment here 😄

**Comment by mholt** [comment]
Oh nice! :) Fancy that...
