### ISSUE TITLE
theme settings seems to be ignored

### ISSUE THREAD

**Issue by mkrueger** [asciinema/asciinema-player#249]
I'm currently making an ansi editor and for the animation part I added an asiciinema export function (as well as video formats).

According to the docs "theme" should work in the header description

Animation:
https://asciinema.org/a/46SkhiCE9yAhCjYGByiKxzAF7

But the theme setting gets ignored:
```
{"version": 2, "width": 80, "height": 23, "timestamp": 0, "title": "millenium", "env": {"TERM": "xterm-256color", "SHELL": "/bin/bash"}, "theme": { "fg": "#aaaaaa", "bg": "#000000", "palette": "#000000:#0000aa:#00aa00:#00aaaa:#aa0000:#aa00aa:#aa5500:#aaaaaa:#555555:#5555ff:#55ff55:#55ffff:#ff5555:#ff55ff:#ffff55:#ffffff" }  }
```

Or do I misunderstood something from https://github.com/asciinema/asciinema/blob/main/doc/asciicast-v2.md?

I should get more dos like colors as output.

One feature request: it would be awesome if line height could be part of the format as well - I need a 1.1em setting for the CP437 stuff my tool can animate. I'll add unicode at some point as well but block chars are quite common in the CP437 scene.

Thanks - awesome project btw.

**Comment by ku1ik** [comment]
Ah, turns out the player doesn't yet implement extraction of a theme from the file.. I completely forgot about that!

There's related idea of adding ability to specify custom format via player's options using the same format as in the cast file (https://github.com/asciinema/asciinema-player/pull/212#issuecomment-1644006552).

I hope to get this in place for v3.7.

**Comment by ku1ik** [comment]
The fix (#256) is ready in will be released soon in v3.7.

Regarding line height:

Adjusting line height is currently the only way of fixing the rendering of block characters, but it's not a 100% solution, as it highly depends on the font and how the OS/browser renders text. I believe the proper/ultimate solution to this problem is to render the block (and other "ascii drawing") characters not with text (as it's done currently) but with canvas or svg, making them use full row height regardless of the line height. This is something I plan to tackle soon :crossed_fingers:

**Comment by ku1ik** [comment]
@mkrueger Does the theme look correct here?

![image](https://github.com/asciinema/asciinema-player/assets/17589/1269893d-8b33-42dc-a915-530c09782693)

**Comment by ku1ik** [comment]
Btw, this is lovely ANSI art!
