### ISSUE TITLE
Rendering  on mobile truncates content (even / especially when full screened)

### ISSUE THREAD

**Issue by talwrii** [asciinema/asciinema-player#61]
Sorry I imagine this one is going to be an utter pain to debug (wooh different versions of browsers on different phones). However, given the amount of content consumption that has moved onto mobiles I think is kind of important: as a case study, I'm unwilling to distribute links to something that won't display on mobiles.

If you try to render some pages (e.g. https://asciinema.org/a/clqz3z43ct1cq7l1i2ocmtvdd) on mobiles (e.g. native chome browser on stock android in nexus 5, android version 6.0.1, chrome 57.0.2987.132) then text is truncated off the screen.

This seems to apply even if:
  i. You record in a smaller window
 ii. You full screen the player

In the example included (https://asciinema.org/a/clqz3z43ct1cq7l1i2ocmtvdd) the text fits on the screen normally (thanks to being recorded in a smaller window). But when you full screen the display this stops working.
m

**Comment by sickill** [comment]
It is very hard to display terminal window on mobile due to the limited screen size. In order for the text to be readable we can't scale it down too much. I tried several approaches, including CSS `font-size`, `scale` and `zoom` but they don't work reliably (one works in one browser, the other works in other browser), or the text is simply too small to read.

I don't have any more ideas (nor time to deal with this), so I'm afraid it's gonna stay like this for now.

**Comment by vityou** [comment]
Lowering the columns to an appropriate number lets it render properly on mobile.  Maybe a solution would be to change the number of columns based on the screen width somewhere in the css or js.

**Comment by sickill** [comment]
The latest version of the player uses text auto-scaling which adapts font size to the available space. This prevents truncation at the cost of text being very small for cases where screen is small while the terminal size during recording was large. I think it's way better than it used to be though. 

If this seems to you like a good enough solution then let's close the issue.
