### ISSUE TITLE
Issue with locally embedded file in Chrome

### ISSUE THREAD

**Issue by securisec** [asciinema/asciinema-player#64]
Hi, is there a fix or a workaround to locally embedded files when opening in Chrome? Chrome and Safari both throws a XMLHttprequest cross origin error. I know the work around is to use a local webserver, but that seems a bit tedious... 

Thanks!

**Comment by sickill** [comment]
Your page is opened via `file://` protocol or the recording URL has `file://` protocol?

**Comment by securisec** [comment]
Hey @sickill . My page is being loaded with the `file://` protocol. the css and js assets for asciinema are saved to local disk. The issue only happens in chrome and safari, but not on firefox.

**Comment by sickill** [comment]
This is a limitation we can't easily overcome. I think it works in other browsers because they're less strict about security of such a setup.

Basically what happens is this: player makes XHR request from a page with `file://` protocol to JSON URL also with `file://` protocol. The protocols are the same but Chrome doesn't allow XHR requests for `file://` protocol. As far as I know Chrome has some flags (or command line switch) that can enable this but I don't remember the details now.

**Comment by inakianduaga** [comment]
So, this is super old but I just run into this and figured out a fix using the [data-uri](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URIs) spec to "inline" the json into the `src` attribute and avoid the CORS preflight. 

Given a `json` file you want to play locally in an  embedded file, 

1. base64 encode the json (using some [online tool](https://www.browserling.com/tools/json-to-base64))
2. use 

```html
<asciinema-player src="data:application/json;base64,BASE_64_ENCODED_JSON_HERE />
```

will work on local files without needing to spin up a server.

**Comment by davidjeddy** [comment]
Wanted to confirm @inakianduaga solution works (though is missing a closing quote at the end of the `src=` property. Note, the Base64 encoded string must be placed INLINE, it can not be a linked file.

Thank you @inakianduaga .

**Comment by sickill** [comment]
Since we can't overcome the limitation of XHR requests, and there's solution (inline, base64 src) I'm gonna close it.
