### ISSUE TITLE
Recording-insensitive display sizing

### ISSUE THREAD

**Issue by cemerick** [asciinema/asciinema-player#68]
I would very much like to (a) not have to bother thinking about the particulars of my recording terminal dimensions (and confront things like #67), and (b) be able to use typical CSS to size the player (in my case, something like `width:100%; height:30em`), and have asciinema figure out what it needs to happen w.r.t. the actual rendering of the terminal content.

Is this possible now and I'm just missing something?…or is the question/suggestion essentially a category error because the nature of the playback mechanism is so strongly tied to terminal rows and columns as recorded?

**Comment by sickill** [comment]
Terminals have 2 buffers: primary buffer (with scrollback) and alternate buffer (also known as "full-screen buffer"). By sending specific esc seq you can switch between these. For example apps like `vim`, `nano`, `less`, `man` switch the terminal to alternate (full-screen) buffer. There can be several reasons, one of them could be that they want to disable any native scrolling as they're doing the scrolling in-app, with their own semantics, and the display some status bar in the last line of terminal.

Now, these full-screen apps use absolute cursor positioning so if you try to replay these sequences in a terminal of smaller size you're gonna get garbage on the screen. For the primary buffer it's usually safe to use terminal of different dimension when replaying as the apps using only primary buffer pretty much just print text, change colors, but they rarely make the cursor jump to absolute position - they more often use relative movement like "move 2 chars left" or "move to the beginning of current line".

I agree that changing the behavior to solve (a) / #67 would be nice, and I'm considering doing it. This is trivial change code-wise. The only issue here is when you record full-screen app like `vim` and you set width/height of the player to smaller values (although it will display fine when doing the opposite, you'd see empty trailing columns/rows then).

**Comment by cemerick** [comment]
Thank you very much for the primer.

FWIW, what I'm doing now is just recording in my typical setting, then using `jq` to normalize to what I know will work in the target web page (specifically, `jq '.width=80|.height=20|.command=null'`). This is working just fine for the content I'm putting out (basic sorts of shell/REPL-esque walkthroughs), so the full-screen thing just is never a concern for me. I suppose if that were different, I'd be mad at the suggestion I made originally. ;-)

**Comment by sickill** [comment]
Regarding b), using typical CSS to size the player, it's actually yes and no :)

If you specify `cols=80 rows=24` then the `<pre>` element that holds the terminal content gets `style="width: 80ch; height: 24em"` (that's "yes"). 

There's however "chrome", like control bar, few px border around the buffer, and the size of these elements are in px, not in characters/lines. Also, if you would do `width: 100%` than there's no way to convert "100% of the player's container" into `XXch`. One option would be to measure how many px this 100% is, and how many px is `1ch` under current display environment (font rendering, pixel density etc all affect the actual sizing), divide one by the other to get `cols` (also taking margin/border and other stuff into account when doing it). That feels unreliable and not worth it to me. So that's a "no" :)

I'd be happy to take it further, so if you have other ideas please shoot. I don't have any good idea as of this moment :)

**Comment by sickill** [comment]
430b7f8 solves a). Feel free to re-open if you want to further discuss player sizing with CSS.

**Comment by sickill** [comment]
If you want to use it right away then `git pull && lein cljsbuild once release` (but I'm sure you know that ;-)

**Comment by cemerick** [comment]
Yup, looks good, thank you! 👍
