### ISSUE TITLE
Decide on licensing

### ISSUE THREAD

**Issue by sickill** [asciinema/asciinema-player#7]
I settled on GPLv3 but some people say it's not compatible with ClojureScript's EPL. Needs further investigation.

**Comment by sickill** [comment]
I settled on GPLv3 but some people say it's not compatible with ClojureScript's EPL. Needs further investigation.

**Comment by gdamore** [comment]
If you just want to ensure that copyleft applies to your own files, without "tainting" other files, or preventing incompatibilities due to conflicts, you can use something that is non-viral in nature, such as a file-scoped copyleft.  I believe the MPL v2.0 is widely considered the best choice if a file-based copyleft is your desire.  However, IANAL.

My layman's read of the EPL suggests that it may be incompatible with GPL licenses, because of contradicting license terms.  Again, IANAL.

You can also probably pose queries about this to SFLC (Eben Moglen) who will probably offer simple advise on a pro-bono basis for your open source efforts.  Obviously, Eben *is* a lawyer. :-)
