### ISSUE TITLE
Running asciinema-player in Jupyter

### ISSUE THREAD

**Issue by deeplook** [asciinema/asciinema-player#85]
Trying to render asciinema screencasts in Jupyter I've used the CSS and JS from https://github.com/asciinema/asciinema-player/releases/tag/v2.6.1 which works great for vanilla HTML, but when adding them in various ways to Jupyter (`%%html`, `%%javascript` or `from IPython.core.display import HTML, Javascript`), I’m getting `Error: Module name "react" has not been loaded yet for context: _. Use require([]) http://requirejs.org`. 

It would be nice to have a recommended solution for this, or maybe even some kind of "plugin" for Jupyter.

**Comment by sickill** [comment]
I'm not familiar with Jupyter unfortunately.

The command line player writes text (not bytes) to stdout: https://github.com/asciinema/asciinema/blob/develop/asciinema/player.py#L74

It first tries to open `/dev/tty` as stdin in order to handle keyboard shortcuts (space, dot, ctrl+c etc): https://github.com/asciinema/asciinema/blob/develop/asciinema/player.py#L14

Not sure if Jupyter runs the command with proper TTY allocated, maybe the problems is somewhere here... Just a wild guess.

**Comment by zodiacfireworks** [comment]
Hi @deeplook, look at asciinema/asciinema#282 ;)

**Comment by sickill** [comment]
The latest (3.0) web player should be way more embedding friendly, if you still have this use case I suggest to try it out.
